#!/usr/bin/env python

import sys

from stan_if.rqt_stan_if import StanUI
from rqt_gui.main import Main

plugin = 'stan_if.rqt_stan_if.StanUI'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
