#!/usr/bin/env python

import sys

from stan_ui.stan_ui_module import StanUiPlugin
from rqt_gui.main import Main

plugin = 'stan_ui.stan_ui_module.StanUiPlugin'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin, plugin_argument_provider=StanUiPlugin.add_arguments))
