#!/usr/bin/env python

import sys

from stan_interface.stanui import StanUI
from rqt_gui.main import Main

plugin = 'stan_interface'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
